create table if not exists public.series_records (
  id bigint generated by default as identity primary key,
  series_id bigint not null references public.series(id) on delete restrict,
  title text not null,
  body_text text,
  image_path text,
  entry_date date not null,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists series_records_public_order_idx
  on public.series_records (series_id, entry_date desc, id desc)
  where deleted_at is null;

alter table public.series_records enable row level security;

grant select on public.series_records to anon, authenticated;
grant select, insert, update, delete on public.series_records to authenticated;
grant usage, select on sequence public.series_records_id_seq to authenticated;

create policy "published series records are readable"
  on public.series_records for select
  to anon, authenticated
  using (
    deleted_at is null
    and exists (
      select 1
      from public.series
      where public.series.id = public.series_records.series_id
        and public.series.deleted_at is null
        and public.series.is_active = true
    )
  );

create policy "admins manage series records"
  on public.series_records for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());
