-- Portfolio Vero Anderson - Supabase baseline schema
--
-- This migration intentionally uses snake_case PostgreSQL names. The application
-- adapter will map them to the existing TypeScript camelCase interface later.
-- It does not import the current SQLite seed data or any production content.

create table if not exists public.manifesto (
  id smallint primary key default 1 check (id = 1),
  statement_text text not null default '',
  image_path_1 text,
  image_path_2 text
);

create table if not exists public.bio (
  id smallint primary key default 1 check (id = 1),
  bio_text text not null default ''
);

create table if not exists public.series (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  essay_text text,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.artworks (
  id bigint generated by default as identity primary key,
  series_id bigint not null references public.series(id) on delete restrict,
  title text not null default 'Sin título',
  year text,
  technique text not null,
  height_cm numeric,
  width_cm numeric,
  availability text not null default 'disponible'
    check (availability in ('disponible', 'coleccion_privada', 'no_disponible')),
  image_path text,
  microstory text,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.settings (
  key text primary key,
  value text not null
);

create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  request_type text not null,
  details text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

-- Application-level admin allowlist. Passwords remain in Supabase Auth;
-- this table only identifies which Auth users may access the admin panel.
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- Persistent rate-limit state. The API will store a keyed hash of the client
-- address, never the raw IP address.
create table if not exists public.rate_limit_buckets (
  scope text not null,
  subject_hash text not null,
  window_started_at timestamptz not null default now(),
  request_count integer not null default 0 check (request_count >= 0),
  primary key (scope, subject_hash)
);

create index if not exists series_public_order_idx
  on public.series (display_order, id)
  where deleted_at is null and is_active = true;

create index if not exists artworks_series_public_order_idx
  on public.artworks (series_id, display_order, id)
  where deleted_at is null;

create index if not exists contact_requests_inbox_idx
  on public.contact_requests (created_at desc, id desc)
  where deleted_at is null;

create index if not exists contact_requests_unread_idx
  on public.contact_requests (is_read, created_at desc)
  where deleted_at is null and is_read = false;

create index if not exists rate_limit_window_idx
  on public.rate_limit_buckets (window_started_at);

-- SECURITY DEFINER is intentional: it lets policies ask whether the current
-- Auth user is an admin without exposing admin_users to anonymous clients.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  );
$$;

-- Atomic database-backed limiter for serverless instances. It is granted only
-- to service_role; the application invokes it with the server-only Supabase key.
create or replace function public.consume_rate_limit(
  p_scope text,
  p_subject_hash text,
  p_window_seconds integer,
  p_max_requests integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  allowed boolean;
begin
  if p_scope is null or p_scope = ''
     or p_subject_hash is null or p_subject_hash = ''
     or p_window_seconds <= 0
     or p_max_requests <= 0 then
    raise exception 'Invalid rate-limit parameters';
  end if;

  insert into public.rate_limit_buckets as buckets (
    scope, subject_hash, window_started_at, request_count
  )
  values (p_scope, p_subject_hash, now(), 1)
  on conflict (scope, subject_hash) do update
  set window_started_at = case
        when now() - buckets.window_started_at
             >= make_interval(secs => p_window_seconds)
          then now()
        else buckets.window_started_at
      end,
      request_count = case
        when now() - buckets.window_started_at
             >= make_interval(secs => p_window_seconds)
          then 1
        else buckets.request_count + 1
      end
  returning request_count <= p_max_requests into allowed;

  return allowed;
end;
$$;

revoke all on function public.is_admin() from public, anon, authenticated;
grant execute on function public.is_admin() to authenticated, service_role;
revoke all on function public.consume_rate_limit(text, text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.consume_rate_limit(text, text, integer, integer)
  to service_role;

-- RLS is enabled everywhere. The server-only service key bypasses these rules;
-- browser clients use the policies below.
alter table public.manifesto enable row level security;
alter table public.bio enable row level security;
alter table public.series enable row level security;
alter table public.artworks enable row level security;
alter table public.settings enable row level security;
alter table public.contact_requests enable row level security;
alter table public.admin_users enable row level security;
alter table public.rate_limit_buckets enable row level security;

-- Explicit grants keep the migration independent from project-level default
-- privileges. RLS remains the authorization boundary.
grant select on public.manifesto, public.bio, public.series, public.artworks
  to anon, authenticated;
grant select, insert, update, delete on
  public.manifesto,
  public.bio,
  public.series,
  public.artworks,
  public.settings,
  public.contact_requests,
  public.admin_users
  to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create policy "published manifesto is readable"
  on public.manifesto for select
  to anon, authenticated
  using (true);

create policy "published bio is readable"
  on public.bio for select
  to anon, authenticated
  using (true);

create policy "published series are readable"
  on public.series for select
  to anon, authenticated
  using (deleted_at is null and is_active = true);

create policy "published artworks are readable"
  on public.artworks for select
  to anon, authenticated
  using (
    deleted_at is null
    and exists (
      select 1
      from public.series
      where public.series.id = public.artworks.series_id
        and public.series.deleted_at is null
        and public.series.is_active = true
    )
  );

create policy "admins manage manifesto"
  on public.manifesto for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "admins manage bio"
  on public.bio for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "admins manage series"
  on public.series for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "admins manage artworks"
  on public.artworks for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "admins manage settings"
  on public.settings for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "admins manage contacts"
  on public.contact_requests for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "admins read admin allowlist"
  on public.admin_users for select
  to authenticated
  using (public.is_admin());

-- Storage is configured here so the application and its permissions are
-- reproducible. Files are uploaded to this public bucket only after browser
-- compression in the later Storage phase.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'portfolio-images',
  'portfolio-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "portfolio images are publicly readable"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'portfolio-images');

create policy "admins upload portfolio images"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'portfolio-images'
    and public.is_admin()
  );

create policy "admins update portfolio images"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'portfolio-images'
    and public.is_admin()
  )
  with check (
    bucket_id = 'portfolio-images'
    and public.is_admin()
  );

create policy "admins delete portfolio images"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'portfolio-images'
    and public.is_admin()
  );