begin;

alter table public.bio rename to biography_sections;
alter table public.biography_sections rename column bio_text to body_text;

alter table public.biography_sections drop constraint if exists bio_id_check;
alter table public.biography_sections alter column id drop default;
alter table public.biography_sections alter column id type bigint using id::bigint;
alter table public.biography_sections alter column id add generated by default as identity;

alter table public.biography_sections
  add column subtitle text,
  add column heading_level text not null default 'large',
  add column display_order integer not null default 0,
  add column is_active boolean not null default true,
  add column created_at timestamptz not null default now(),
  add column updated_at timestamptz not null default now(),
  add column deleted_at timestamptz;

select setval(
  pg_get_serial_sequence('public.biography_sections', 'id'),
  coalesce((select max(id) from public.biography_sections), 0) + 1,
  false
);

alter table public.biography_sections
  add constraint biography_sections_body_text_not_empty
    check (length(btrim(body_text)) > 0),
  add constraint biography_sections_heading_level_check
    check (heading_level in ('large', 'medium', 'small')),
  add constraint biography_sections_display_order_check
    check (display_order >= 0);

create index if not exists biography_sections_order_idx
  on public.biography_sections (display_order, id)
  where deleted_at is null;

drop policy if exists "published bio is readable" on public.biography_sections;
drop policy if exists "admins manage bio" on public.biography_sections;

revoke all on table public.biography_sections from anon, authenticated, service_role;
grant select on table public.biography_sections to anon, authenticated, service_role;
grant insert, update on table public.biography_sections to authenticated, service_role;

create policy "published biography sections are readable"
  on public.biography_sections for select
  to anon
  using (deleted_at is null and is_active = true);

create policy "users and admins read biography sections"
  on public.biography_sections for select
  to authenticated
  using (deleted_at is null and (is_active = true or (select public.is_admin())));

create policy "admins create biography sections"
  on public.biography_sections for insert
  to authenticated
  with check ((select public.is_admin()));

create policy "admins update biography sections"
  on public.biography_sections for update
  to authenticated
  using ((select public.is_admin()) and deleted_at is null)
  with check ((select public.is_admin()));

create or replace function public.reorder_biography_sections(p_ordered_ids bigint[])
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  expected_count integer;
  incoming_count integer;
begin
  select count(*)::integer
    into expected_count
    from public.biography_sections
   where deleted_at is null;

  incoming_count := coalesce(array_length(p_ordered_ids, 1), 0);

  if incoming_count <> expected_count then
    raise exception 'La lista de orden debe incluir todas las secciones activas y ocultas no eliminadas';
  end if;

  if exists (
    select 1
      from unnest(coalesce(p_ordered_ids, '{}'::bigint[])) as item(id)
     group by item.id
    having count(*) > 1
  ) then
    raise exception 'La lista de orden no puede contener IDs duplicados';
  end if;

  if exists (
    select id
      from public.biography_sections
     where deleted_at is null
    except
    select item.id
      from unnest(coalesce(p_ordered_ids, '{}'::bigint[])) as item(id)
  ) then
    raise exception 'La lista de orden contiene secciones faltantes';
  end if;

  if exists (
    select item.id
      from unnest(coalesce(p_ordered_ids, '{}'::bigint[])) as item(id)
    except
    select id
      from public.biography_sections
     where deleted_at is null
  ) then
    raise exception 'La lista de orden contiene IDs inválidos';
  end if;

  update public.biography_sections as section
     set display_order = ordered.position - 1,
         updated_at = now()
    from unnest(p_ordered_ids) with ordinality as ordered(id, position)
   where section.id = ordered.id
     and section.deleted_at is null;
end;
$$;

revoke all on function public.reorder_biography_sections(bigint[])
  from public, anon, authenticated;
grant execute on function public.reorder_biography_sections(bigint[])
  to service_role;

commit;
